# Generated by Django 3.1.5 on 2021-02-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinevotingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.IntegerField(),
        ),
    ]
